server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    password: 1234
    url: jdbc:postgresql://postgres:5432/fraud
    username: postgres
  zipkin:
    base-url: http://zipkin:9411
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false